import type { Movie } from "../interfaces";

export const seedMovies: Movie[] = [
  {
    id: "seed-1",
    title: "Interstellar",
    year: 2014,
    type: "film",
    genre: "Bilim Kurgu",
    status: "bitti",
    rating: 5,
    posterUrl: "",
    note: "Zaman ve sevgi üzerine görsel bir şölen. Son yarım saat efsane.",
    createdAt: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "seed-2",
    title: "Breaking Bad",
    year: 2008,
    type: "dizi",
    genre: "Dram",
    status: "bitti",
    rating: 5,
    posterUrl: "",
    note: "Karakter gelişiminin ders kitabı.",
    createdAt: "2026-01-12T10:00:00.000Z",
  },
  {
    id: "seed-3",
    title: "Dune: Part Two",
    year: 2024,
    type: "film",
    genre: "Bilim Kurgu",
    status: "izleniyor",
    rating: 4,
    posterUrl: "",
    note: "Görüntü yönetimi inanılmaz.",
    createdAt: "2026-01-15T10:00:00.000Z",
  },
  {
    id: "seed-4",
    title: "The Bear",
    year: 2022,
    type: "dizi",
    genre: "Komedi",
    status: "izlenecek",
    rating: 0,
    posterUrl: "",
    note: "",
    createdAt: "2026-01-18T10:00:00.000Z",
  },
  {
    id: "seed-5",
    title: "Parazit",
    year: 2019,
    type: "film",
    genre: "Gerilim",
    status: "bitti",
    rating: 5,
    posterUrl: "",
    note: "Sınıf farkını anlatan en zekice kurgu.",
    createdAt: "2026-01-20T10:00:00.000Z",
  },
];
